spring:
  application:
    name: wizard-stat-aggregator
  profiles:
    default: local
  exposed:
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
