spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wizard_stat_db
    username: wizard_user
    password: wizard_pass
    driver-class-name: org.postgresql.Driver

infrastructure:
  http:
    client:
      lands-17:
        base-url: https://www.17lands.com
